[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:tts]
command=uv run --directory /app/tts /app/tts/tts_server.py
directory=/app
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/var/log/tts.err.log
stdout_logfile=/var/log/tts.out.log
